# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

#trigger:
 # tags:
  #  include:
   # - v*

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: "Use DotNet Core 3.0 Preview 6 SDK"
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview6-012264'

- task: DotNetCoreCLI@2
  displayName: "DotNet Restore"
  inputs:
    command: 'restore'
    projects: 'src/**/*.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "DotNet Build"
  inputs:
    command: 'build'
    projects: 'src/**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: "DotNet Test"
  inputs:
    command: 'test'
    projects: 'src/**/*.csproj'