@host = localhost:16604

### api
POST http://@{{host}}/api

### api/comparepackage
POST http://@{{host}}/api/comparepackage
Content-Type: "application/json;"

{
    "name": "LightInject",
    "SourceA": "https://api.nuget.org/v3/",
    "SourceB": "https://api.nuget.org/v3/"
}
### api/comparePackages
POST http://@{{host}}/api/comparepackages
Content-Type: "application/json;"

{
    "SourceComparers": [
        {
            "sourceA": "https://api.nuget.org/v3/",
            "sourceB": "https://api.nuget.org/v3/",
            "Packages": [
                {
                    "name" : "Newtonsoft.Json"
                },
                {
                    "name": "LightInject"
                }
            ]
        }
    ]
}